# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 630f2d66e16ecb62c8a0ccf39f32f03757ee060373544e69a46e4c88dc0e4907c9513ad1b190e0b66df65a275344891bfae047ff1ceb26955b7d5dad7839c921

test:
  secret_key_base: 44216a99722c753f9f9ae5afeb3924e27dc027de3c498e0771491cb0a4c2a511964c6887111689f7731172ddf8cef9e37257129b0b4fc6aca8637706457efc2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
